#include "seObjectiveReaper.h"

#include "Elan Classes/maths.cpp"
#include "Elan Classes/Audio.cpp"
#include "Elan Classes/TagParser.cpp"
#include "Elan Classes/Translator.cpp"
#include "Elan Classes/MidiHelper.cpp"
#include "Elan Classes/Tagger.cpp"
#include "Elan Classes/SignalFunctions.cpp"

#include "Reaper Classes/ReaperClassesHeader.cpp"
#include "Reaper Classes/Env.cpp"
#include "Reaper Classes/Item.cpp"
#include "Reaper Classes/Marker.cpp"
#include "Reaper Classes/StretchMarker.cpp"
#include "Reaper Classes/Take.cpp"
#include "Reaper Classes/Track.cpp"

#include "XenakiosStuff/jcomponents.cpp"
#include "XenakiosStuff/pluginprocessor.cpp"
